AllCops:
  Exclude:
    - 'tmp/**/*'

Metrics/LineLength:
  Max: 120

Lint/AmbiguousRegexpLiteral:
  Exclude:
   - test/**/features/**/*.rb

Lint/ParenthesesAsGroupedExpression:
  Exclude:
   - spec/**/*
